src/app/@theme/components/header/header.component.html, src/app/@theme/layouts/one-column/one-column.layout.ts, src/app/@theme/layouts/sample/sample.layout.ts, src/app/@theme/layouts/three-columns/three-columns.layout.ts, src/app/@theme/layouts/two-columns/two-columns.layout.ts, src/app/@theme/styles/themes.scss, src/index.html
=> mejorando tamaño de fuentes, componentes, padding, margin general

src/app/@core/utils/autentication.service.ts, src/app/@theme/components/header/header.component.ts, src/app/pages/forms/form-inputs/form-inputs.component.html, src/app/pages/pages-menu.ts
=> General style

package.json
=> añadiendo configuración externa  para docker

src/app/@theme/components/dinamicform/dinamicform.component.html, src/app/@theme/components/dinamicform/dinamicform.component.ts, src/app/pages/inscripciones/posgrado/datos-personales.ts
=> Form dinamico

src/app/@theme/components/dinamicform/dinamicform.component.ts, src/app/app-config.ts, src/app/pages/inscripciones/info-basica/info-basica.component.ts
=> arreglo de if en dinamicform

src/app/@core/data/persona.service.ts, src/app/@theme/components/dinamicform/dinamicform.component.html, src/app/@theme/components/dinamicform/dinamicform.component.scss, src/app/@theme/components/dinamicform/dinamicform.component.ts, src/app/pages/inscripciones/info-basica/form-persona.ts, src/app/pages/inscripciones/info-basica/info-basica.component.html, src/app/pages/inscripciones/info-basica/info-basica.component.ts
=> Modulo datos basicos

src/app/@theme/components/dinamicform/dinamicform.component.html, src/app/@theme/components/dinamicform/dinamicform.component.ts
=> correccion y configuracion del componente dinamic form

src/app/@core/data/menu.service.ts, src/app/app-config.ts, src/app/pages/pages.component.ts, src/app/pages/pages.module.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
Ajuste de la carga del menú a través de un service.ts
=> Ajuste de menu con creación de service

src/app/@theme/components/nuxeo/nuxeo.component.ts, src/app/pages/inscripciones/posgrado/informacion-contacto/informacion-contacto.component.html
=> limpiando prueba de servicio de nuxeo

src/app/app-config.ts
=> cambio url api personas

src/app/@core/data/menu.service.ts, src/app/app.component.ts, src/app/pages/genero/crud-genero/crud-genero.component.ts, src/app/pages/pages-menu.ts, src/app/pages/pages.component.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
=> Ajuste internacionalización form generado

src/app/pages/genero/genero.module.ts, src/app/pages/genero/list-genero/list-genero.component.html, src/app/pages/genero/list-genero/list-genero.component.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
=> Ajuste internacionalización form generado y smart-table parte1

src/assets/i18n/en.json, src/assets/i18n/es.json
=> traducciones en menu

src/app/@core/utils/autentication.service.ts, src/app/@core/utils/nuxeo.service.ts
=> resolviendo build

src/app/@theme/components/dinamicform/dinamicform.component.html, src/app/@theme/components/dinamicform/dinamicform.component.scss
=> Dynamicform style theming material

src/app/@theme/components/dinamicform/dinamicform.component.html, src/app/@theme/components/dinamicform/dinamicform.component.scss
=> hidesetfield option and fix spaces webkit

src/app/@theme/components/dinamicform/dinamicform.component.scss, src/app/@theme/components/header/header.component.html, src/app/@theme/components/theme-switcher/theme-switcher.component.scss, src/app/@theme/styles/styles.scss, src/app/@theme/styles/themes.scss
=> Nuevo estilo default!!

src/app/app-config.ts, src/app/pages/pages.component.ts
=> Ajustes de menú con autenticación

src/app/@core/data/persona.service.ts, src/main.ts
=> probando autenticación

src/app/pages/pages-menu.ts, src/app/pages/pages.component.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
=> Tablas parametricas

src/app/@core/data/campus_mid.service.ts, src/app/@core/data/ubicaciones.service.ts, src/app/app-config.ts, src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts, src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts, src/app/pages/info_persona/info_persona.module.ts, src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts, src/app/pages/inscripcion/inscripcion.module.ts, src/app/pages/inscripcion/posgrado/posgrado.component.ts
=> Ajusteform

src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts, src/app/pages/info_caracteristica/crud-info_caracteristica/form-info_caracteristica.ts, src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.html, src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts, src/app/pages/informacion_contacto/crud-informacion_contacto/form-informacion_contacto.ts, src/assets/i18n/en.json, src/assets/i18n/es.json
=> Ajusteform - cambios en formularios 1

src/app/@theme/styles/themes.scss, src/app/pages/info_caracteristica/info_caracteristica-routing.module.ts, src/app/pages/info_caracteristica/info_caracteristica.module.ts, src/app/pages/info_caracteristica/view-info_caracteristica/view-info_caracteristica.component.html, src/app/pages/info_caracteristica/view-info_caracteristica/view-info_caracteristica.component.spec.ts, src/app/pages/info_caracteristica/view-info_caracteristica/view-info_caracteristica.component.ts, src/app/pages/info_persona/info_persona-routing.module.ts, src/app/pages/info_persona/info_persona.module.ts, src/app/pages/info_persona/view-info-persona/view-info-persona.component.html, src/app/pages/info_persona/view-info-persona/view-info-persona.component.scss, src/app/pages/info_persona/view-info-persona/view-info-persona.component.spec.ts, src/app/pages/info_persona/view-info-persona/view-info-persona.component.ts, src/app/pages/informacion_contacto/informacion_contacto-routing.module.ts, src/app/pages/informacion_contacto/informacion_contacto.module.ts, src/app/pages/informacion_contacto/view-informacion_contacto/view-informacion_contacto.component.html, src/app/pages/informacion_contacto/view-informacion_contacto/view-informacion_contacto.component.spec.ts, src/app/pages/informacion_contacto/view-informacion_contacto/view-informacion_contacto.component.ts, src/app/pages/inscripcion/inscripcion-routing.module.ts, src/app/pages/inscripcion/perfil/perfil.component.html, src/app/pages/inscripcion/perfil/perfil.component.spec.ts, src/app/pages/inscripcion/perfil/perfil.component.ts, src/app/pages/inscripcion/posgrado/posgrado.component.html, src/app/pages/inscripcion/posgrado/posgrado.component.scss, src/app/pages/inscripcion/posgrado/posgrado.component.ts
=> Visualizacion componentes

src/app/pages/inscripcion/perfil/perfil.component.html, src/app/pages/inscripcion/perfil/perfil.component.ts, src/app/pages/inscripcion/posgrado/posgrado.component.html, src/app/pages/inscripcion/posgrado/posgrado.component.scss, src/app/pages/inscripcion/posgrado/posgrado.component.ts
=> mejora y cambio para recibir id sobre componente perfil

src/app/@theme/components/dinamicform/dinamicform.component.ts
=> resolviendo errores de dinamicform

src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts, src/app/pages/info_persona/view-info-persona/view-info-persona.component.ts, src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
=> Tipo identificacion

src/app/@theme/components/dinamicform/dinamicform.component.ts, src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.html, src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts, src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.html, src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts, src/app/pages/info_persona/view-info-persona/view-info-persona.component.ts, src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.html, src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts, src/app/pages/inscripcion/posgrado/posgrado.component.html, src/app/pages/inscripcion/posgrado/posgrado.component.ts
=> porcentaje y recarga segun acciones

src/app/pages/inscripcion/posgrado/posgrado.component.html, src/app/pages/inscripcion/posgrado/posgrado.component.ts
=> barra de porcentage a cada elemento

src/app/@theme/components/dinamicform/dinamicform.component.ts
=> correccion bug modelo_data!

src/app/@core/utils/nuxeo.service.ts, src/app/@theme/components/dinamicform/dinamicform.component.ts, src/app/app-config.ts, src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
=> Formacion academica

src/app/app-config.ts
=> cableando a preprod_local

package-lock.json, src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
=> resolviendo despliegue

src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts, src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.ts, src/app/pages/inscripcion/posgrado/posgrado.component.html
=> se agrega variable para obtener ente del usuario logueado en experiencia

src/app/app-config.ts
=> cableando wso2

src/app/app-config.ts
=> cableando configuracion

src/app/app-config.ts
=> configuracion

src/app/@core/data/menu.service.ts, src/app/pages/pages.component.ts
=> añadiendo cabecera a get de menu

src/app/@core/data/menu.service.ts, src/app/app-config.ts, src/app/pages/pages.component.ts
=> añadiendo header a configuración

src/app/pages/inscripcion/posgrado/posgrado.component.html, src/app/pages/inscripcion/posgrado/posgrado.component.ts
=> corrección ventana activa y opciones mientras se tenga ente

src/app/app-config.ts
=> set variable preprod_local

src/app/@core/utils/implicit_autentication.service.ts, src/app/app-config.ts
=> Ngx admin 4 7 18

src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts, src/app/pages/experiencia_laboral/crud-experiencia_laboral/form-experiencia_laboral.ts, src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
=> Creación, actualización y carga de soporte de nuxeo

src/app/app-config.ts
=> ajustes wso2 endpoints nube

src/app/@core/data/admisiones.service.ts, src/app/app-config.ts, src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts, src/environments/environment.prod.ts, src/environments/environment.ts
=> Enviroment conf

package-lock.json, package.json
=> ajustes endpoints prod wso2

.drone.yml, src/app/pages/inscripcion/posgrado/posgrado.component.html
=> ajustes drone yml para despliegues prueba!

src/app/@core/_Interceptor/auth.Interceptor.ts, src/app/@core/core.module.ts, src/app/@core/data/campus_mid.service.ts, src/app/@core/data/documento.service.ts, src/app/@core/data/ente.service.ts, src/app/@core/data/experiencia.service.ts, src/app/@core/data/formacion_academica.service.ts, src/app/@core/data/idioma.service.ts, src/app/@core/data/menu.service.ts, src/app/@core/data/organizacion.service.ts, src/app/@core/data/persona.service.ts, src/app/@core/data/programa_academico.service.ts, src/app/@core/data/ubicaciones.service.ts, src/app/app-config.ts, src/app/pages/pages.component.ts, src/environments/environment.ts
=> Interceptors

.drone.yml
=> ajuste yml por version ngrx

.drone.yml
=> Ajuste de drone para despliegue

.drone.yml, package-lock.json
=> remove update

.drone.yml
=> Ajuste drone.yml

src/app/pages/pages.component.ts
=> ajuste menú
